[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "koopmotion"
version = "0.0.1"
description = "Koopman-based learning from demonstrations"
authors = [{name="Alice Kate Li"}]
dependencies = []

